### ISSUE TITLE
Links to FEC.gov pages don't work on new Page layout sections

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-pattern-library#106]
**What we're after:** Upon clicking on any one of the links listed on the Page layout templates, users should be taken to the hyperlinked page. However, upon clicking, users are taken to a blank version of that page template. 

**Example:**
<img width="930" alt="screen shot 2018-04-09 at 10 28 13 am" src="https://user-images.githubusercontent.com/31663028/38503737-d11f21ce-3be0-11e8-8b67-74791aa370eb.png">

**Comment by jenniferthibault** [comment]
Thanks for identifying this issue @JonellaCulmer ! I can take a look and see what might be causing this

**Comment by jenniferthibault** [comment]
This looks like a problem caused by how we're using iframes to generate this content. The iframe needed to be told to allow a certain type of behavior, like linking to an external link, or opening a link in a new tab. Since these are a list of examples someone might want to see at the same time, I think opening in a new tab is a desired behavior here.

This article was super helpful to understand what was happening and finding the right solution:
[Play safely in sandboxed IFrames, by Mike West](https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/)

Fix is in via #107, this issue can be closed when that is merged

**Comment by JonellaCulmer** [comment]
This work has been merged, so closing.

https://fec-pattern-library.app.cloud.gov/docs/page-layouts/collection-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/commissioner-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/custom-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/document-feed-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/meeting-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/reporting-example-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/reports-landing-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/resource-page.html
https://fec-pattern-library.app.cloud.gov/docs/page-layouts/update-pages.html
