### ISSUE TITLE
[Sync] Command Injection [High Risk]

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-pattern-library#121]
During 5/16/18 log review found 1 high risk issue - Command Injection
https://snyk.io/test/github/fecgov/fec-pattern-library?severity=high&severity=medium&severity=low
Vulnerable module: shelljs
shelljs is a portable Unix shell commands for Node.js.

Affected version of this package are vulnerable to Command Injection. It is possible to invoke commands from  shell.exec() from external sources, allowing an attacker to inject arbitrary commands.

**Comment by lbeaufort** [comment]
After receiving a response from the Fractal github repository and upon further investigation by the team, we have concluded that since shelljs is only used for initial installation of the fractal project and not currently used in any other capacity, we can conclude that the risk is highly reduced and is not exploitable within our code base. This issue is now closed.
https://github.com/fecgov/fec-pattern-library/issues/113#issuecomment-387508142
